### ISSUE TITLE
Support for investment transactions

### ISSUE THREAD

**Issue by darkms** [kedder/ofxstatement#128]
Hi, thanks for this awesome project!

Just wanted to let you know that I've implemented support for investment transactions rendered to OFX in [my fork](https://github.com/kedder/ofxstatement/compare/master...darkms:invest-transactions) ([exporter plugin](https://github.com/gerasiov/ofxstatement-russian/compare/master...darkms:support-tinkoff-investments-broker)). The output OFX works more or less OK with KMyMoney.

Would you be interested in having such a feature supported in this repo? (I'll raise a PR if yes)

**Comment by kedder** [comment]
Hi @darkms! I think this feature makes sense, fits in the scope of `ofxstatement` and I welcome the pull request :)

One thing I suggest is to create another sample ofx file to test investment transactions instead of modifying the existing one (and writing a separate test for investment transactions). I find it easier to debug isolated tests when things break.

**Comment by darkms** [comment]
Thx @kedder, made a few changes as you've advised and raised a PR #129
