### ISSUE TITLE
plugin is outdated

### ISSUE THREAD

**Issue by terokorp** [kedder/ofxstatement#27]
Plugin banking.statements.osuuspankki is outdated and dosen't work, but it has one fork which works fine. https://github.com/vukk/banking.statements.osuuspankki
Would it be better to put to plugins list instead of that broken one?

**Comment by petri** [comment]
Issue reports and pull requests welcome. (I am the author of b.s.o.)

**Comment by terokorp** [comment]
I'm just user who tried to use b.s.o and got weird errors. I pinpointed problem to transaction type maping and then find out that someone has already fixed those problems.
( https://github.com/vukk/banking.statements.osuuspankki/commit/76b942e7c71403981841323884e83e120d6f1ffc )
So, link to working version is on my first comment and that is not my repo and I don't want to send pull reuqests from others repos, if that's even possible.

Original b.s.o repo was been so long time untouced (abt 2½ year) and fix for this bug has been made over one year ago, so I thought original b.s.o was already dead.

**Comment by petri** [comment]
Thats's all fine and dandy @terokorp, I understand. Can you submit a bug report to b.s.o? And @vukk, could you please submit a pull request after that?

**Comment by vukk** [comment]
Since there is no issue raised at b.s.o yet, I'll note this here:
My fork removes functionality, namely the transaction types. Some (many?) consumers of ofx statements only support CREDIT/DEBIT types, so it's a good default. I think this is what is observed here.

But maybe the additional types should be made optional (e.g. config file) instead of fully removing them.

Also the fork code is untested on OP corporate CSVs, since I did not have access to these for testing.

**Comment by petri** [comment]
Thanks for explaining, @vukk. AFAIK, ofxstatement is not a tool for ONLY GnuCash, and multiple transaction types (there are almost twenty) are part of the OFX standard. The types are very useful and outright absolutely needed for some other use cases. Therefore, removing functionality is NOT an option in my opinion and this issue here reported by @terokorp should be closed as invalid.

However, I do agree that some sort of "compatibility mode" would be a good idea and it's good that this issue of compatibility was brought up. BUT - it would have to be supported by all the plugins and driven by the author of ofxstatement... @kedder, what's your thoughts on this?

**Comment by petri** [comment]
I added #28 for this. Please let's continue the discussion there? (and close this issue)

**Comment by kedder** [comment]
Hm, guys, do you think it would be reasonable to make the output configurable on `b.s.o` level, in similar way this plugin is configured: https://github.com/kedder/ofxstatement-lithuanian/blob/master/src/ofxstatement/plugins/danske.py#L47. That way user can ask the plugin to produce the output he wants (with the sensible default, of course).

Would it make both kinds of users happy (ones that use it for GnuCash, and ones that need more precise ofx markup)?

**Comment by petri** [comment]
Please see my suggestion at #28 ...

**Comment by kedder** [comment]
(I'm not sure whether #28 is better place for this, but since discussion happens here, responding here as well)

@petri, I see some practical problems with this approach (ofxstatement core manages a list of all possible plugin "capabilities"). 

1. A capability, as you described it, is not just a boolean, it is an _interface_, that plugin promises to comply with. So ofxstatement suddenly have to document these interfaces, and, perhaps, provide a way to check for compliance. Otherwise, what does it mean for plugin to implement `GNUCASH_RESTRICTED_OFX` capability? Plugins will eventually implement a "feature" in different incompatible way and this central mechanism for reporting "capabilities" will became pretty useless.
2. There is a huge impedance for plugin authors to add a new "capability": they have to think how to make it generic enough so it can be usable/implementable by other plugins, they have to get their pull request accepted by ofxstatement maintainer. And after all (my own assessment), most of plugin authors couldn't care less about this stuff, they just want their statements parsed, so they won't be interested in compliance with these capabilities too much.   
3. It will put a burdain on me to carefully understand all the features other plugins offer, maintain sensible and understandable list of capabilities, try to detect duplicate "capabilities". Also, there will be basically no practical way to refactor this list of capabilities, join some together into more "generic" ones, or split too generic capabilities into several more specific -- it will involve changing plugins that implement these capabilities, something I don't want to deal with.  
4. Finally, this can only support boolean "flags", and doesn't address configuration for capabilities in any way.

This is why I would like to leave such features and variances in behaviour to plugins themselves, via their private configuration options. We can invest some effort into making supported configuration options more discoverable by users, but I'd like to have it in informal way (e.g. as docstring), rather than formal (e.g. configuration schemas, interfaces, etc), because complexity of formal approach seems too high for the purpose.

**Comment by petri** [comment]
I already suggested (see above) to continue this on #28 ... but:

My suggestion was meant to document the capabilities of plugins for the benefit of users of ofxstatement.

To rephrase, I did not mean to treat this as a matter of enforcing strict interface compliance - instead, more like a matter of documentation, really. 

And perhaps I chose my words badly above when I spoke of "defining capabilities": I would merely hope that ofxstatement &@kedded could perhaps step in to do some arbitration if plugin authors implementing similar stuff can't agree on something. Which should be a rare occasion.

But I am happy if we just have some documented way of documenting discovering the capabilities. For that, a boolean flag in a capabilities dict is sufficient to me.

**Comment by MirkoDziadzka** [comment]
Hi

I'm not sure if the existing plugins are really the right place for these features. 

As I understand them, they are more about converting an arbitrary input to OFX. Some of them are doing filtering. For example, I contributed stuff to merge some lines on some credit card statements. This was probably not the right place to do this but the only place I could added this back then.

Maybe a better place would be an additional OFX filter phase, where filter plugins can be registered to work on the OFX data and rewrite them before the output. This would make these features orthogonal to the input parsing and it would be possible to add an 'gnucash' filter which rewrites all the stuff that gnucash don't like.

**Comment by petri** [comment]
Please, @kedder can you close this so we can continue on #28? I changed its title to better reflect the issue at hand, and summarized what's been discussed here.

**Comment by kedder** [comment]
Ok
